version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: cd backend
      - run: yarn install

  build2:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: cd frontend
      - run: yarn install
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - build1
